import fs from 'node:fs';
import path from 'node:path';
import {expect, it} from '@jest/globals';

it('ships usable Android inventory, resource-pack menu, and follow-latest chat controls', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'App.tsx'), 'utf8');
  expect(source).toContain('Microsoft sign-in');
  expect(source).toContain('Auto reconnect');
  expect(source).toContain('Message after changing servers');
  expect(source).toContain('Inventory');
  expect(source).toContain('Auto-deposit inventory');
  expect(source).toContain('Auto-deposit range (1–16 blocks)');
  expect(source).toContain('Nearest container');
  expect(source).toContain('AFK Desk 0.9.2');
  expect(source).toContain('console: {height: 440');
  expect(source).toContain('<ScrollView ref={logListRef} style={styles.logList} nestedScrollEnabled');
  expect(source).not.toContain('<FlatList ref={logListRef}');
  expect(source).toContain("action: 'drop-stack'");
  expect(source).toContain('Drop this stack?');
  expect(source).toContain("type === 'window'");
  expect(source).toContain('<ServerMenuModal');
  expect(source).toContain('resourceIcon');
  expect(source).toContain('Follow latest');
  expect(source).toContain('nestedScrollEnabled');
  expect(source).toContain('SUPPORTED_GAME_VERSIONS');
  expect(source).toContain('Automatic (detect from server)');
  expect(source).toContain('<VersionField');
  expect(source).toContain("action: 'complete-chat'");
  expect(source).toContain('chatSuggestions');
  expect(source).toContain('activateChatClick');
  expect(source).toContain("click.action === 'run_command'");
  expect(source).toContain("click.action === 'open_url'");
});
